name: Python Test Workflor
on: [push]

jobs:
  build: 
    name: Python Test

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Print Hello World
        run: |
          python ./hello-world.py

      - name: Use secret variable
        run: echo "secret value:" $SECRET_VARIABLE
        env:
          SECRET_VARIABLE: ${{ secrets.SECRET_VARIABLE }}