name: Python Test Workflor
on: [push]

jobs:
  build: 
    name: Python Test

    runs-on: ubuntu-latest

    steps: 
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Print Hello World
        run: |
          python hello-world.py